// Create data
var data = [{
        "height": 1570,
        "size": "S"
    }, {
        "height": 1978,
        "size": "XXL"
    }, {
        "height": 1697,
        "size": "M"
    }, {
        "height": 1467,
        "size": "S"
    }, {
        "height": 1742,
        "size": "L"
    }, {
        "height": 1793,
        "size": "L"
    }, {
        "height": 1594,
        "size": "S"
    }, {
        "height": 1658,
        "size": "M"
    }, {
        "height": 1677,
        "size": "M"
    }, {
        "height": 1401,
        "size": "S"
    }, {
        "height": 1956,
        "size": "XXL"
    }, {
        "height": 1892,
        "size": "XL"
    }, {
        "height": 1754,
        "size": "L"
    }, {
        "height": 1880,
        "size": "XL"
    }, {
        "height": 1442,
        "size": "S"
    }, {
        "height": 1415,
        "size": "S"
    }, {
        "height": 1514,
        "size": "S"
    }, {
        "height": 1836,
        "size": "XL"
    }, {
        "height": 1892,
        "size": "XL"
    }, {
        "height": 1936,
        "size": "XXL"
    }, {
        "height": 1554,
        "size": "S"
    }, {
        "height": 1509,
        "size": "S"
    }, {
        "height": 1937,
        "size": "XXL"
    }, {
        "height": 1601,
        "size": "S"
    }, {
        "height": 1713,
        "size": "L"
    }, {
        "height": 1445,
        "size": "S"
    }, {
        "height": 1937,
        "size": "XXL"
    }, {
        "height": 1729,
        "size": "L"
    }, {
        "height": 1711,
        "size": "L"
    }, {
        "height": 1647,
        "size": "S"
    }, {
        "height": 1940,
        "size": "XXL"
    }, {
        "height": 1695,
        "size": "M"
    }, {
        "height": 1940,
        "size": "XXL"
    }, {
        "height": 1725,
        "size": "L"
    }, {
        "height": 1688,
        "size": "M"
    }, {
        "height": 1419,
        "size": "S"
    }, {
        "height": 1789,
        "size": "L"
    }, {
        "height": 1505,
        "size": "S"
    }, {
        "height": 1731,
        "size": "L"
    }, {
        "height": 1542,
        "size": "S"
    }, {
        "height": 1705,
        "size": "L"
    }, {
        "height": 1418,
        "size": "S"
    }, {
        "height": 1699,
        "size": "M"
    }, {
        "height": 1577,
        "size": "S"
    }, {
        "height": 1840,
        "size": "XL"
    }, {
        "height": 1969,
        "size": "XXL"
    }, {
        "height": 1588,
        "size": "S"
    }, {
        "height": 1432,
        "size": "S"
    }, {
        "height": 1812,
        "size": "XL"
    }, {
        "height": 1488,
        "size": "S"
    }, {
        "height": 1706,
        "size": "L"
    }, {
        "height": 1634,
        "size": "S"
    }, {
        "height": 1994,
        "size": "XXL"
    }, {
        "height": 1993,
        "size": "XXL"
    }, {
        "height": 1658,
        "size": "M"
    }, {
        "height": 1698,
        "size": "M"
    }, {
        "height": 1436,
        "size": "S"
    }, {
        "height": 1713,
        "size": "L"
    }, {
        "height": 1714,
        "size": "L"
    }, {
        "height": 1865,
        "size": "XL"
    }, {
        "height": 1402,
        "size": "S"
    }, {
        "height": 1821,
        "size": "XL"
    }, {
        "height": 1590,
        "size": "S"
    }, {
        "height": 1834,
        "size": "XL"
    }, {
        "height": 1769,
        "size": "L"
    }, {
        "height": 1554,
        "size": "S"
    }, {
        "height": 1896,
        "size": "XL"
    }, {
        "height": 1924,
        "size": "XXL"
    }, {
        "height": 1807,
        "size": "XL"
    }, {
        "height": 1439,
        "size": "S"
    }, {
        "height": 1891,
        "size": "XL"
    }, {
        "height": 1835,
        "size": "XL"
    }, {
        "height": 1523,
        "size": "S"
    }, {
        "height": 1486,
        "size": "S"
    }, {
        "height": 1901,
        "size": "XXL"
    }, {
        "height": 1715,
        "size": "L"
    }, {
        "height": 1507,
        "size": "S"
    }, {
        "height": 1904,
        "size": "XXL"
    }, {
        "height": 1761,
        "size": "L"
    }, {
        "height": 1667,
        "size": "M"
    }, {
        "height": 1720,
        "size": "L"
    }, {
        "height": 1671,
        "size": "M"
    }, {
        "height": 1924,
        "size": "XXL"
    }, {
        "height": 1888,
        "size": "XL"
    }, {
        "height": 1572,
        "size": "S"
    }, {
        "height": 1420,
        "size": "S"
    }, {
        "height": 1568,
        "size": "S"
    }, {
        "height": 1806,
        "size": "XL"
    }, {
        "height": 1596,
        "size": "S"
    }, {
        "height": 1893,
        "size": "XL"
    }, {
        "height": 1532,
        "size": "S"
    }, {
        "height": 1911,
        "size": "XXL"
    }, {
        "height": 1517,
        "size": "S"
    }, {
        "height": 1409,
        "size": "S"
    }, {
        "height": 1498,
        "size": "S"
    }, {
        "height": 1869,
        "size": "XL"
    }, {
        "height": 1628,
        "size": "S"
    }, {
        "height": 1885,
        "size": "XL"
    }, {
        "height": 1742,
        "size": "L"
    }, {
        "height": 1755,
        "size": "L"
    }, {
        "height": 1735,
        "size": "L"
    }, {
        "height": 1801,
        "size": "XL"
    }, {
        "height": 1703,
        "size": "L"
    }, {
        "height": 1445,
        "size": "S"
    }, {
        "height": 1475,
        "size": "S"
    }, {
        "height": 1633,
        "size": "S"
    }, {
        "height": 1501,
        "size": "S"
    }, {
        "height": 1530,
        "size": "S"
    }, {
        "height": 1943,
        "size": "XXL"
    }, {
        "height": 1526,
        "size": "S"
    }, {
        "height": 1508,
        "size": "S"
    }, {
        "height": 1773,
        "size": "L"
    }, {
        "height": 1767,
        "size": "L"
    }, {
        "height": 1730,
        "size": "L"
    }, {
        "height": 1835,
        "size": "XL"
    }, {
        "height": 1601,
        "size": "S"
    }, {
        "height": 1457,
        "size": "S"
    }, {
        "height": 1780,
        "size": "L"
    }, {
        "height": 1552,
        "size": "S"
    }, {
        "height": 1727,
        "size": "L"
    }, {
        "height": 1530,
        "size": "S"
    }, {
        "height": 1891,
        "size": "XL"
    }, {
        "height": 1753,
        "size": "L"
    }, {
        "height": 1987,
        "size": "XXL"
    }, {
        "height": 1912,
        "size": "XXL"
    }, {
        "height": 1493,
        "size": "S"
    }, {
        "height": 1536,
        "size": "S"
    }, {
        "height": 1495,
        "size": "S"
    }, {
        "height": 1639,
        "size": "S"
    }, {
        "height": 1452,
        "size": "S"
    }, {
        "height": 1879,
        "size": "XL"
    }, {
        "height": 1806,
        "size": "XL"
    }, {
        "height": 1660,
        "size": "M"
    }, {
        "height": 1880,
        "size": "XL"
    }, {
        "height": 1695,
        "size": "M"
    }, {
        "height": 1953,
        "size": "XXL"
    }, {
        "height": 1517,
        "size": "S"
    }, {
        "height": 1565,
        "size": "S"
    }, {
        "height": 1953,
        "size": "XXL"
    }, {
        "height": 1457,
        "size": "S"
    }, {
        "height": 1431,
        "size": "S"
    }, {
        "height": 1635,
        "size": "S"
    }, {
        "height": 1586,
        "size": "S"
    }, {
        "height": 1753,
        "size": "L"
    }, {
        "height": 1444,
        "size": "S"
    }, {
        "height": 1585,
        "size": "S"
    }, {
        "height": 1455,
        "size": "S"
    }, {
        "height": 1494,
        "size": "S"
    }, {
        "height": 1480,
        "size": "S"
    }, {
        "height": 1556,
        "size": "S"
    }, {
        "height": 1514,
        "size": "S"
    }, {
        "height": 1448,
        "size": "S"
    }, {
        "height": 1658,
        "size": "M"
    }, {
        "height": 1652,
        "size": "M"
    }, {
        "height": 1822,
        "size": "XL"
    }, {
        "height": 1601,
        "size": "S"
    }, {
        "height": 1565,
        "size": "S"
    }, {
        "height": 1622,
        "size": "S"
    }, {
        "height": 1805,
        "size": "XL"
    }, {
        "height": 1750,
        "size": "L"
    }, {
        "height": 1538,
        "size": "S"
    }, {
        "height": 1581,
        "size": "S"
    }, {
        "height": 1957,
        "size": "XXL"
    }, {
        "height": 1885,
        "size": "XL"
    }, {
        "height": 1601,
        "size": "S"
    }, {
        "height": 1921,
        "size": "XXL"
    }, {
        "height": 1523,
        "size": "S"
    }, {
        "height": 1662,
        "size": "M"
    }, {
        "height": 1625,
        "size": "S"
    }, {
        "height": 1987,
        "size": "XXL"
    }, {
        "height": 1668,
        "size": "M"
    }, {
        "height": 1487,
        "size": "S"
    }, {
        "height": 1507,
        "size": "S"
    }, {
        "height": 1774,
        "size": "L"
    }, {
        "height": 1599,
        "size": "S"
    }, {
        "height": 1741,
        "size": "L"
    }, {
        "height": 1777,
        "size": "L"
    }, {
        "height": 1428,
        "size": "S"
    }, {
        "height": 1504,
        "size": "S"
    }, {
        "height": 1916,
        "size": "XXL"
    }, {
        "height": 1928,
        "size": "XXL"
    }, {
        "height": 1774,
        "size": "L"
    }, {
        "height": 1656,
        "size": "M"
    }, {
        "height": 1966,
        "size": "XXL"
    }, {
        "height": 1774,
        "size": "L"
    }, {
        "height": 1907,
        "size": "XXL"
    }, {
        "height": 1718,
        "size": "L"
    }, {
        "height": 1889,
        "size": "XL"
    }, {
        "height": 1674,
        "size": "M"
    }, {
        "height": 1803,
        "size": "XL"
    }, {
        "height": 1841,
        "size": "XL"
    }, {
        "height": 1546,
        "size": "S"
    }, {
        "height": 1515,
        "size": "S"
    }, {
        "height": 1802,
        "size": "XL"
    }, {
        "height": 1819,
        "size": "XL"
    }, {
        "height": 1664,
        "size": "M"
    }, {
        "height": 1886,
        "size": "XL"
    }, {
        "height": 1888,
        "size": "XL"
    }, {
        "height": 1977,
        "size": "XXL"
    }, {
        "height": 1624,
        "size": "S"
    }, {
        "height": 1427,
        "size": "S"
    }, {
        "height": 1660,
        "size": "M"
    }, {
        "height": 1754,
        "size": "L"
    }, {
        "height": 1784,
        "size": "L"
    }, {
        "height": 1477,
        "size": "S"
    }, {
        "height": 1920,
        "size": "XXL"
    }, {
        "height": 1775,
        "size": "L"
    }, {
        "height": 1440,
        "size": "S"
    }, {
        "height": 1838,
        "size": "XL"
    }, {
        "height": 1813,
        "size": "XL"
    }, {
        "height": 1836,
        "size": "XL"
    }, {
        "height": 1756,
        "size": "L"
    }, {
        "height": 1893,
        "size": "XL"
    }, {
        "height": 1962,
        "size": "XXL"
    }, {
        "height": 1987,
        "size": "XXL"
    }, {
        "height": 1933,
        "size": "XXL"
    }, {
        "height": 1628,
        "size": "S"
    }, {
        "height": 1791,
        "size": "L"
    }, {
        "height": 1769,
        "size": "L"
    }, {
        "height": 1970,
        "size": "XXL"
    }, {
        "height": 1656,
        "size": "M"
    }, {
        "height": 1693,
        "size": "M"
    }, {
        "height": 1677,
        "size": "M"
    }, {
        "height": 1742,
        "size": "L"
    }, {
        "height": 1719,
        "size": "L"
    }, {
        "height": 1402,
        "size": "S"
    }, {
        "height": 1906,
        "size": "XXL"
    }, {
        "height": 1665,
        "size": "M"
    }, {
        "height": 1503,
        "size": "S"
    }, {
        "height": 1705,
        "size": "L"
    }, {
        "height": 1901,
        "size": "XXL"
    }, {
        "height": 1897,
        "size": "XL"
    }, {
        "height": 1971,
        "size": "XXL"
    }, {
        "height": 1438,
        "size": "S"
    }, {
        "height": 1676,
        "size": "M"
    }, {
        "height": 1773,
        "size": "L"
    }, {
        "height": 1827,
        "size": "XL"
    }, {
        "height": 1965,
        "size": "XXL"
    }, {
        "height": 1533,
        "size": "S"
    }, {
        "height": 1789,
        "size": "L"
    }, {
        "height": 1990,
        "size": "XXL"
    }, {
        "height": 1545,
        "size": "S"
    }, {
        "height": 1740,
        "size": "L"
    }, {
        "height": 1708,
        "size": "L"
    }, {
        "height": 1426,
        "size": "S"
    }, {
        "height": 1409,
        "size": "S"
    }, {
        "height": 1959,
        "size": "XXL"
    }, {
        "height": 1502,
        "size": "S"
    }, {
        "height": 1793,
        "size": "L"
    }, {
        "height": 1524,
        "size": "S"
    }, {
        "height": 1884,
        "size": "XL"
    }, {
        "height": 1649,
        "size": "S"
    }, {
        "height": 1878,
        "size": "XL"
    }, {
        "height": 1814,
        "size": "XL"
    }, {
        "height": 1822,
        "size": "XL"
    }, {
        "height": 1784,
        "size": "L"
    }, {
        "height": 1483,
        "size": "S"
    }, {
        "height": 1689,
        "size": "M"
    }, {
        "height": 1844,
        "size": "XL"
    }, {
        "height": 1726,
        "size": "L"
    }, {
        "height": 1723,
        "size": "L"
    }, {
        "height": 1535,
        "size": "S"
    }, {
        "height": 1813,
        "size": "XL"
    }, {
        "height": 1874,
        "size": "XL"
    }, {
        "height": 1627,
        "size": "S"
    }, {
        "height": 1575,
        "size": "S"
    }, {
        "height": 1624,
        "size": "S"
    }, {
        "height": 1885,
        "size": "XL"
    }, {
        "height": 1692,
        "size": "M"
    }, {
        "height": 1894,
        "size": "XL"
    }, {
        "height": 1796,
        "size": "L"
    }, {
        "height": 1405,
        "size": "S"
    }, {
        "height": 1999,
        "size": "XXL"
    }, {
        "height": 1733,
        "size": "L"
    }, {
        "height": 1568,
        "size": "S"
    }, {
        "height": 1544,
        "size": "S"
    }, {
        "height": 1945,
        "size": "XXL"
    }, {
        "height": 1732,
        "size": "L"
    }, {
        "height": 1840,
        "size": "XL"
    }, {
        "height": 1903,
        "size": "XXL"
    }, {
        "height": 1438,
        "size": "S"
    }, {
        "height": 1996,
        "size": "XXL"
    }, {
        "height": 1401,
        "size": "S"
    }, {
        "height": 1636,
        "size": "S"
    }, {
        "height": 1668,
        "size": "M"
    }, {
        "height": 1594,
        "size": "S"
    }, {
        "height": 1669,
        "size": "M"
    }, {
        "height": 1974,
        "size": "XXL"
    }, {
        "height": 1799,
        "size": "L"
    }, {
        "height": 1764,
        "size": "L"
    }, {
        "height": 1494,
        "size": "S"
    }, {
        "height": 1667,
        "size": "M"
    }, {
        "height": 1678,
        "size": "M"
    }, {
        "height": 1512,
        "size": "S"
    }, {
        "height": 1703,
        "size": "L"
    },
    {
        "height": 1877,
        "size": "XL"
    }, {
        "height": 1684,
        "size": "M"
    }, {
        "height": 1444,
        "size": "S"
    }, {
        "height": 1556,
        "size": "S"
    }, {
        "height": 1982,
        "size": "XXL"
    }, {
        "height": 1645,
        "size": "S"
    }, {
        "height": 1683,
        "size": "M"
    }, {
        "height": 1530,
        "size": "S"
    }, {
        "height": 1520,
        "size": "S"
    }, {
        "height": 1432,
        "size": "S"
    }, {
        "height": 1765,
        "size": "L"
    }, {
        "height": 1687,
        "size": "M"
    }, {
        "height": 1716,
        "size": "L"
    }, {
        "height": 1783,
        "size": "L"
    }, {
        "height": 1689,
        "size": "M"
    }, {
        "height": 1445,
        "size": "S"
    }, {
        "height": 1420,
        "size": "S"
    }, {
        "height": 1666,
        "size": "M"
    }, {
        "height": 1843,
        "size": "XL"
    }, {
        "height": 1901,
        "size": "XXL"
    }, {
        "height": 1742,
        "size": "L"
    }, {
        "height": 1857,
        "size": "XL"
    }, {
        "height": 1507,
        "size": "S"
    }, {
        "height": 1439,
        "size": "S"
    }, {
        "height": 1584,
        "size": "S"
    }, {
        "height": 1550,
        "size": "S"
    }, {
        "height": 1406,
        "size": "S"
    }, {
        "height": 1717,
        "size": "L"
    }, {
        "height": 1723,
        "size": "L"
    }, {
        "height": 1419,
        "size": "S"
    }, {
        "height": 1831,
        "size": "XL"
    }, {
        "height": 1586,
        "size": "S"
    }, {
        "height": 1785,
        "size": "L"
    }, {
        "height": 1826,
        "size": "XL"
    }, {
        "height": 1772,
        "size": "L"
    }, {
        "height": 1806,
        "size": "XL"
    }, {
        "height": 1892,
        "size": "XL"
    }, {
        "height": 1558,
        "size": "S"
    }, {
        "height": 1428,
        "size": "S"
    }, {
        "height": 1728,
        "size": "L"
    }, {
        "height": 1831,
        "size": "XL"
    }, {
        "height": 1990,
        "size": "XXL"
    }, {
        "height": 1441,
        "size": "S"
    }, {
        "height": 1502,
        "size": "S"
    }, {
        "height": 1879,
        "size": "XL"
    }, {
        "height": 1980,
        "size": "XXL"
    }, {
        "height": 1676,
        "size": "M"
    }, {
        "height": 1830,
        "size": "XL"
    }, {
        "height": 1524,
        "size": "S"
    }, {
        "height": 1701,
        "size": "L"
    }, {
        "height": 1956,
        "size": "XXL"
    }, {
        "height": 1460,
        "size": "S"
    }, {
        "height": 1739,
        "size": "L"
    }, {
        "height": 1784,
        "size": "L"
    }, {
        "height": 1405,
        "size": "S"
    }, {
        "height": 1783,
        "size": "L"
    }, {
        "height": 1986,
        "size": "XXL"
    }, {
        "height": 1833,
        "size": "XL"
    }, {
        "height": 1910,
        "size": "XXL"
    }, {
        "height": 1934,
        "size": "XXL"
    }, {
        "height": 1988,
        "size": "XXL"
    }, {
        "height": 1454,
        "size": "S"
    }, {
        "height": 1851,
        "size": "XL"
    }, {
        "height": 1434,
        "size": "S"
    }, {
        "height": 1406,
        "size": "S"
    }, {
        "height": 1675,
        "size": "M"
    }, {
        "height": 1848,
        "size": "XL"
    }, {
        "height": 1547,
        "size": "S"
    }, {
        "height": 1738,
        "size": "L"
    }, {
        "height": 1773,
        "size": "L"
    }, {
        "height": 1575,
        "size": "S"
    }, {
        "height": 1859,
        "size": "XL"
    }, {
        "height": 1477,
        "size": "S"
    }, {
        "height": 1456,
        "size": "S"
    }, {
        "height": 1465,
        "size": "S"
    }, {
        "height": 1894,
        "size": "XL"
    }, {
        "height": 1763,
        "size": "L"
    }, {
        "height": 1614,
        "size": "S"
    }, {
        "height": 1485,
        "size": "S"
    }, {
        "height": 1437,
        "size": "S"
    }, {
        "height": 1649,
        "size": "S"
    }, {
        "height": 1889,
        "size": "XL"
    }, {
        "height": 1976,
        "size": "XXL"
    }, {
        "height": 1609,
        "size": "S"
    }, {
        "height": 1648,
        "size": "S"
    }, {
        "height": 1964,
        "size": "XXL"
    }, {
        "height": 1748,
        "size": "L"
    }, {
        "height": 1772,
        "size": "L"
    }, {
        "height": 1901,
        "size": "XXL"
    }, {
        "height": 1547,
        "size": "S"
    }, {
        "height": 1862,
        "size": "XL"
    }, {
        "height": 1803,
        "size": "XL"
    }, {
        "height": 1709,
        "size": "L"
    }, {
        "height": 1861,
        "size": "XL"
    }, {
        "height": 1788,
        "size": "L"
    }, {
        "height": 1826,
        "size": "XL"
    }, {
        "height": 1982,
        "size": "XXL"
    }, {
        "height": 1830,
        "size": "XL"
    }, {
        "height": 1462,
        "size": "S"
    }, {
        "height": 1813,
        "size": "XL"
    }, {
        "height": 1838,
        "size": "XL"
    }, {
        "height": 1946,
        "size": "XXL"
    }, {
        "height": 1918,
        "size": "XXL"
    }, {
        "height": 1571,
        "size": "S"
    }, {
        "height": 1736,
        "size": "L"
    }, {
        "height": 1536,
        "size": "S"
    }, {
        "height": 1575,
        "size": "S"
    }, {
        "height": 1585,
        "size": "S"
    }, {
        "height": 1909,
        "size": "XXL"
    }, {
        "height": 1651,
        "size": "M"
    }, {
        "height": 1661,
        "size": "M"
    }, {
        "height": 1869,
        "size": "XL"
    }, {
        "height": 1859,
        "size": "XL"
    }, {
        "height": 1447,
        "size": "S"
    }, {
        "height": 1605,
        "size": "S"
    }, {
        "height": 1475,
        "size": "S"
    }, {
        "height": 1437,
        "size": "S"
    }, {
        "height": 1662,
        "size": "M"
    }, {
        "height": 1897,
        "size": "XL"
    }, {
        "height": 1511,
        "size": "S"
    }, {
        "height": 1547,
        "size": "S"
    }, {
        "height": 1608,
        "size": "S"
    }, {
        "height": 1933,
        "size": "XXL"
    }, {
        "height": 1823,
        "size": "XL"
    }, {
        "height": 1774,
        "size": "L"
    }, {
        "height": 1767,
        "size": "L"
    }, {
        "height": 1761,
        "size": "L"
    }, {
        "height": 1978,
        "size": "XXL"
    }, {
        "height": 1441,
        "size": "S"
    }, {
        "height": 1402,
        "size": "S"
    }, {
        "height": 1557,
        "size": "S"
    }, {
        "height": 1782,
        "size": "L"
    }, {
        "height": 1516,
        "size": "S"
    }, {
        "height": 1948,
        "size": "XXL"
    }, {
        "height": 1696,
        "size": "M"
    }, {
        "height": 1705,
        "size": "L"
    }, {
        "height": 1542,
        "size": "S"
    }, {
        "height": 1641,
        "size": "S"
    }, {
        "height": 1980,
        "size": "XXL"
    }, {
        "height": 1518,
        "size": "S"
    }, {
        "height": 1980,
        "size": "XXL"
    }, {
        "height": 1933,
        "size": "XXL"
    }, {
        "height": 1893,
        "size": "XL"
    }, {
        "height": 1831,
        "size": "XL"
    }, {
        "height": 1890,
        "size": "XL"
    }, {
        "height": 1599,
        "size": "S"
    }, {
        "height": 1836,
        "size": "XL"
    }, {
        "height": 1982,
        "size": "XXL"
    }, {
        "height": 1625,
        "size": "S"
    }, {
        "height": 1763,
        "size": "L"
    }, {
        "height": 1862,
        "size": "XL"
    }, {
        "height": 1703,
        "size": "L"
    }, {
        "height": 1905,
        "size": "XXL"
    }, {
        "height": 1419,
        "size": "S"
    }, {
        "height": 1401,
        "size": "S"
    }, {
        "height": 1404,
        "size": "S"
    }, {
        "height": 1680,
        "size": "M"
    }, {
        "height": 1459,
        "size": "S"
    }, {
        "height": 1905,
        "size": "XXL"
    }, {
        "height": 1911,
        "size": "XXL"
    }, {
        "height": 1404,
        "size": "S"
    }, {
        "height": 1946,
        "size": "XXL"
    }, {
        "height": 1988,
        "size": "XXL"
    }, {
        "height": 1890,
        "size": "XL"
    }, {
        "height": 1541,
        "size": "S"
    }, {
        "height": 1922,
        "size": "XXL"
    }, {
        "height": 1859,
        "size": "XL"
    }, {
        "height": 1663,
        "size": "M"
    }, {
        "height": 1497,
        "size": "S"
    }, {
        "height": 1906,
        "size": "XXL"
    }, {
        "height": 1629,
        "size": "S"
    }, {
        "height": 1613,
        "size": "S"
    }, {
        "height": 1637,
        "size": "S"
    }, {
        "height": 1883,
        "size": "XL"
    }, {
        "height": 1470,
        "size": "S"
    }, {
        "height": 1658,
        "size": "M"
    }, {
        "height": 1671,
        "size": "M"
    }, {
        "height": 1703,
        "size": "L"
    }, {
        "height": 1857,
        "size": "XL"
    }, {
        "height": 1944,
        "size": "XXL"
    }, {
        "height": 1895,
        "size": "XL"
    }, {
        "height": 1968,
        "size": "XXL"
    }, {
        "height": 1976,
        "size": "XXL"
    }, {
        "height": 1485,
        "size": "S"
    }, {
        "height": 1429,
        "size": "S"
    }, {
        "height": 1490,
        "size": "S"
    }, {
        "height": 1990,
        "size": "XXL"
    }, {
        "height": 1445,
        "size": "S"
    }, {
        "height": 1410,
        "size": "S"
    }, {
        "height": 1544,
        "size": "S"
    }, {
        "height": 1574,
        "size": "S"
    }, {
        "height": 1765,
        "size": "L"
    }, {
        "height": 1830,
        "size": "XL"
    }, {
        "height": 1508,
        "size": "S"
    }, {
        "height": 1918,
        "size": "XXL"
    }, {
        "height": 1481,
        "size": "S"
    }, {
        "height": 1956,
        "size": "XXL"
    }, {
        "height": 1652,
        "size": "M"
    }, {
        "height": 1691,
        "size": "M"
    }, {
        "height": 1490,
        "size": "S"
    }, {
        "height": 1828,
        "size": "XL"
    }, {
        "height": 1483,
        "size": "S"
    }, {
        "height": 1612,
        "size": "S"
    }, {
        "height": 1945,
        "size": "XXL"
    }, {
        "height": 1807,
        "size": "XL"
    }, {
        "height": 1643,
        "size": "S"
    }, {
        "height": 1810,
        "size": "XL"
    }, {
        "height": 1778,
        "size": "L"
    }, {
        "height": 1846,
        "size": "XL"
    }, {
        "height": 1972,
        "size": "XXL"
    }, {
        "height": 1967,
        "size": "XXL"
    }, {
        "height": 1933,
        "size": "XXL"
    }, {
        "height": 1920,
        "size": "XXL"
    }, {
        "height": 1452,
        "size": "S"
    }, {
        "height": 1686,
        "size": "M"
    }, {
        "height": 1518,
        "size": "S"
    }, {
        "height": 1763,
        "size": "L"
    }, {
        "height": 1528,
        "size": "S"
    }, {
        "height": 1404,
        "size": "S"
    }, {
        "height": 1823,
        "size": "XL"
    }, {
        "height": 1822,
        "size": "XL"
    }, {
        "height": 1693,
        "size": "M"
    }, {
        "height": 1798,
        "size": "L"
    }, {
        "height": 1587,
        "size": "S"
    }, {
        "height": 1400,
        "size": "S"
    }, {
        "height": 1511,
        "size": "S"
    }, {
        "height": 1569,
        "size": "S"
    }, {
        "height": 1597,
        "size": "S"
    }, {
        "height": 1444,
        "size": "S"
    }, {
        "height": 1580,
        "size": "S"
    }, {
        "height": 1946,
        "size": "XXL"
    }, {
        "height": 1577,
        "size": "S"
    }, {
        "height": 1593,
        "size": "S"
    }, {
        "height": 1957,
        "size": "XXL"
    }, {
        "height": 1458,
        "size": "S"
    }, {
        "height": 1748,
        "size": "L"
    }, {
        "height": 1705,
        "size": "L"
    }, {
        "height": 1795,
        "size": "L"
    }, {
        "height": 1642,
        "size": "S"
    }, {
        "height": 1538,
        "size": "S"
    }, {
        "height": 1977,
        "size": "XXL"
    }, {
        "height": 1790,
        "size": "L"
    }, {
        "height": 1685,
        "size": "M"
    }, {
        "height": 1585,
        "size": "S"
    }, {
        "height": 1940,
        "size": "XXL"
    }, {
        "height": 1941,
        "size": "XXL"
    }, {
        "height": 1620,
        "size": "S"
    }, {
        "height": 1677,
        "size": "M"
    }, {
        "height": 1582,
        "size": "S"
    }, {
        "height": 1842,
        "size": "XL"
    }, {
        "height": 1432,
        "size": "S"
    }, {
        "height": 1496,
        "size": "S"
    }, {
        "height": 1886,
        "size": "XL"
    }, {
        "height": 1534,
        "size": "S"
    }, {
        "height": 1484,
        "size": "S"
    }, {
        "height": 1989,
        "size": "XXL"
    }, {
        "height": 1947,
        "size": "XXL"
    }, {
        "height": 1472,
        "size": "S"
    }, {
        "height": 1850,
        "size": "XL"
    }, {
        "height": 1954,
        "size": "XXL"
    }, {
        "height": 1781,
        "size": "L"
    }, {
        "height": 1953,
        "size": "XXL"
    }, {
        "height": 1481,
        "size": "S"
    }, {
        "height": 1552,
        "size": "S"
    }, {
        "height": 1404,
        "size": "S"
    }, {
        "height": 1981,
        "size": "XXL"
    }, {
        "height": 1965,
        "size": "XXL"
    }, {
        "height": 1855,
        "size": "XL"
    }, {
        "height": 1565,
        "size": "S"
    }, {
        "height": 1938,
        "size": "XXL"
    }, {
        "height": 1611,
        "size": "S"
    }, {
        "height": 1702,
        "size": "L"
    }, {
        "height": 1445,
        "size": "S"
    }, {
        "height": 1499,
        "size": "S"
    }, {
        "height": 1932,
        "size": "XXL"
    }, {
        "height": 1543,
        "size": "S"
    }, {
        "height": 1940,
        "size": "XXL"
    }, {
        "height": 1893,
        "size": "XL"
    }, {
        "height": 1676,
        "size": "M"
    }, {
        "height": 1817,
        "size": "XL"
    }, {
        "height": 1706,
        "size": "L"
    }, {
        "height": 1753,
        "size": "L"
    }, {
        "height": 1716,
        "size": "L"
    }, {
        "height": 1852,
        "size": "XL"
    }, {
        "height": 1800,
        "size": "L"
    }, {
        "height": 1753,
        "size": "L"
    }, {
        "height": 1972,
        "size": "XXL"
    }, {
        "height": 1836,
        "size": "XL"
    }, {
        "height": 1763,
        "size": "L"
    }, {
        "height": 1749,
        "size": "L"
    }, {
        "height": 1756,
        "size": "L"
    }, {
        "height": 1517,
        "size": "S"
    }, {
        "height": 1919,
        "size": "XXL"
    }, {
        "height": 1535,
        "size": "S"
    }, {
        "height": 1741,
        "size": "L"
    }, {
        "height": 1914,
        "size": "XXL"
    }, {
        "height": 1826,
        "size": "XL"
    }, {
        "height": 1728,
        "size": "L"
    }, {
        "height": 1577,
        "size": "S"
    }, {
        "height": 1534,
        "size": "S"
    }, {
        "height": 1947,
        "size": "XXL"
    }, {
        "height": 1477,
        "size": "S"
    }, {
        "height": 1654,
        "size": "M"
    }, {
        "height": 1933,
        "size": "XXL"
    }, {
        "height": 1907,
        "size": "XXL"
    }, {
        "height": 1957,
        "size": "XXL"
    }, {
        "height": 1789,
        "size": "L"
    }, {
        "height": 1907,
        "size": "XXL"
    }, {
        "height": 1694,
        "size": "M"
    }, {
        "height": 1454,
        "size": "S"
    }, {
        "height": 1820,
        "size": "XL"
    }, {
        "height": 1645,
        "size": "S"
    }, {
        "height": 1959,
        "size": "XXL"
    }, {
        "height": 1442,
        "size": "S"
    }, {
        "height": 1840,
        "size": "XL"
    }, {
        "height": 1783,
        "size": "L"
    }, {
        "height": 1690,
        "size": "M"
    }, {
        "height": 1693,
        "size": "M"
    }, {
        "height": 1890,
        "size": "XL"
    }, {
        "height": 1449,
        "size": "S"
    }, {
        "height": 1463,
        "size": "S"
    }, {
        "height": 1557,
        "size": "S"
    }, {
        "height": 1699,
        "size": "M"
    }, {
        "height": 1831,
        "size": "XL"
    }, {
        "height": 1647,
        "size": "S"
    }, {
        "height": 1559,
        "size": "S"
    }, {
        "height": 1877,
        "size": "XL"
    }, {
        "height": 1805,
        "size": "XL"
    }, {
        "height": 1644,
        "size": "S"
    }, {
        "height": 1896,
        "size": "XL"
    }, {
        "height": 1633,
        "size": "S"
    }, {
        "height": 1696,
        "size": "M"
    }, {
        "height": 1625,
        "size": "S"
    }, {
        "height": 1585,
        "size": "S"
    }, {
        "height": 1699,
        "size": "M"
    }, {
        "height": 1889,
        "size": "XL"
    }, {
        "height": 1665,
        "size": "M"
    }, {
        "height": 1891,
        "size": "XL"
    }, {
        "height": 1586,
        "size": "S"
    }, {
        "height": 1481,
        "size": "S"
    }, {
        "height": 1578,
        "size": "S"
    }, {
        "height": 1905,
        "size": "XXL"
    }, {
        "height": 1670,
        "size": "M"
    }, {
        "height": 1761,
        "size": "L"
    }, {
        "height": 1630,
        "size": "S"
    }, {
        "height": 1891,
        "size": "XL"
    }, {
        "height": 1793,
        "size": "L"
    }, {
        "height": 1662,
        "size": "M"
    }, {
        "height": 1530,
        "size": "S"
    }, {
        "height": 1425,
        "size": "S"
    }, {
        "height": 1634,
        "size": "S"
    }, {
        "height": 1460,
        "size": "S"
    }, {
        "height": 1502,
        "size": "S"
    }, {
        "height": 1985,
        "size": "XXL"
    }, {
        "height": 1845,
        "size": "XL"
    }, {
        "height": 1450,
        "size": "S"
    }, {
        "height": 1977,
        "size": "XXL"
    }, {
        "height": 1560,
        "size": "S"
    }, {
        "height": 1896,
        "size": "XL"
    }, {
        "height": 1655,
        "size": "M"
    }, {
        "height": 1543,
        "size": "S"
    }, {
        "height": 1887,
        "size": "XL"
    }, {
        "height": 1581,
        "size": "S"
    }, {
        "height": 1560,
        "size": "S"
    }, {
        "height": 1489,
        "size": "S"
    }, {
        "height": 1510,
        "size": "S"
    }, {
        "height": 1500,
        "size": "S"
    }, {
        "height": 1652,
        "size": "M"
    }, {
        "height": 1589,
        "size": "S"
    }, {
        "height": 1592,
        "size": "S"
    }, {
        "height": 1422,
        "size": "S"
    }, {
        "height": 1475,
        "size": "S"
    }, {
        "height": 1789,
        "size": "L"
    }, {
        "height": 1491,
        "size": "S"
    }, {
        "height": 1553,
        "size": "S"
    }, {
        "height": 1425,
        "size": "S"
    }, {
        "height": 1492,
        "size": "S"
    }, {
        "height": 1927,
        "size": "XXL"
    }, {
        "height": 1509,
        "size": "S"
    }, {
        "height": 1878,
        "size": "XL"
    }, {
        "height": 1409,
        "size": "S"
    }, {
        "height": 1593,
        "size": "S"
    }, {
        "height": 1451,
        "size": "S"
    }, {
        "height": 1950,
        "size": "XXL"
    }, {
        "height": 1619,
        "size": "S"
    }, {
        "height": 1926,
        "size": "XXL"
    }, {
        "height": 1967,
        "size": "XXL"
    }, {
        "height": 1892,
        "size": "XL"
    }, {
        "height": 1415,
        "size": "S"
    }, {
        "height": 1800,
        "size": "L"
    }, {
        "height": 1662,
        "size": "M"
    }, {
        "height": 1955,
        "size": "XXL"
    }, {
        "height": 1977,
        "size": "XXL"
    }, {
        "height": 1727,
        "size": "L"
    }, {
        "height": 1456,
        "size": "S"
    }, {
        "height": 1852,
        "size": "XL"
    }, {
        "height": 1865,
        "size": "XL"
    }, {
        "height": 1839,
        "size": "XL"
    }, {
        "height": 1458,
        "size": "S"
    }, {
        "height": 1753,
        "size": "L"
    }, {
        "height": 1902,
        "size": "XXL"
    }, {
        "height": 1649,
        "size": "S"
    }, {
        "height": 1788,
        "size": "L"
    }, {
        "height": 1707,
        "size": "L"
    }, {
        "height": 1729,
        "size": "L"
    }, {
        "height": 1400,
        "size": "S"
    }, {
        "height": 1861,
        "size": "XL"
    }, {
        "height": 1417,
        "size": "S"
    }, {
        "height": 1458,
        "size": "S"
    }, {
        "height": 1894,
        "size": "XL"
    }, {
        "height": 1591,
        "size": "S"
    }, {
        "height": 1936,
        "size": "XXL"
    }, {
        "height": 1618,
        "size": "S"
    }, {
        "height": 1571,
        "size": "S"
    }, {
        "height": 1736,
        "size": "L"
    }, {
        "height": 1663,
        "size": "M"
    }, {
        "height": 1750,
        "size": "L"
    }, {
        "height": 1504,
        "size": "S"
    }, {
        "height": 1670,
        "size": "M"
    }, {
        "height": 1498,
        "size": "S"
    }, {
        "height": 1463,
        "size": "S"
    }, {
        "height": 1561,
        "size": "S"
    }, {
        "height": 1717,
        "size": "L"
    }, {
        "height": 1944,
        "size": "XXL"
    }, {
        "height": 1414,
        "size": "S"
    }, {
        "height": 1551,
        "size": "S"
    }, {
        "height": 1733,
        "size": "L"
    }, {
        "height": 1434,
        "size": "S"
    }, {
        "height": 1639,
        "size": "S"
    }, {
        "height": 1667,
        "size": "M"
    }, {
        "height": 1520,
        "size": "S"
    }, {
        "height": 1461,
        "size": "S"
    }, {
        "height": 1604,
        "size": "S"
    }, {
        "height": 1430,
        "size": "S"
    }, {
        "height": 1839,
        "size": "XL"
    }, {
        "height": 1457,
        "size": "S"
    }, {
        "height": 1435,
        "size": "S"
    }, {
        "height": 1479,
        "size": "S"
    }, {
        "height": 1907,
        "size": "XXL"
    }, {
        "height": 1712,
        "size": "L"
    }, {
        "height": 1839,
        "size": "XL"
    }, {
        "height": 1478,
        "size": "S"
    }, {
        "height": 1657,
        "size": "M"
    }, {
        "height": 1828,
        "size": "XL"
    }, {
        "height": 1622,
        "size": "S"
    }, {
        "height": 1728,
        "size": "L"
    }, {
        "height": 1933,
        "size": "XXL"
    }, {
        "height": 1518,
        "size": "S"
    }, {
        "height": 1947,
        "size": "XXL"
    }, {
        "height": 1854,
        "size": "XL"
    }, {
        "height": 1963,
        "size": "XXL"
    }, {
        "height": 1416,
        "size": "S"
    }, {
        "height": 1504,
        "size": "S"
    }, {
        "height": 1768,
        "size": "L"
    }, {
        "height": 1936,
        "size": "XXL"
    }, {
        "height": 1567,
        "size": "S"
    }, {
        "height": 1920,
        "size": "XXL"
    }, {
        "height": 1759,
        "size": "L"
    }, {
        "height": 1447,
        "size": "S"
    }, {
        "height": 1668,
        "size": "M"
    }, {
        "height": 1583,
        "size": "S"
    }, {
        "height": 1953,
        "size": "XXL"
    }, {
        "height": 1486,
        "size": "S"
    }, {
        "height": 1681,
        "size": "M"
    }, {
        "height": 1670,
        "size": "M"
    }, {
        "height": 1485,
        "size": "S"
    }, {
        "height": 1669,
        "size": "M"
    }, {
        "height": 1617,
        "size": "S"
    }, {
        "height": 1799,
        "size": "L"
    }, {
        "height": 1721,
        "size": "L"
    }, {
        "height": 1706,
        "size": "L"
    }, {
        "height": 1864,
        "size": "XL"
    }, {
        "height": 1404,
        "size": "S"
    }, {
        "height": 1763,
        "size": "L"
    }, {
        "height": 1986,
        "size": "XXL"
    }, {
        "height": 1493,
        "size": "S"
    }, {
        "height": 1424,
        "size": "S"
    }, {
        "height": 1847,
        "size": "XL"
    }, {
        "height": 1738,
        "size": "L"
    }, {
        "height": 1477,
        "size": "S"
    }, {
        "height": 1597,
        "size": "S"
    }, {
        "height": 1985,
        "size": "XXL"
    }, {
        "height": 1626,
        "size": "S"
    }, {
        "height": 1469,
        "size": "S"
    }, {
        "height": 1658,
        "size": "M"
    }, {
        "height": 1830,
        "size": "XL"
    }, {
        "height": 1818,
        "size": "XL"
    }, {
        "height": 1589,
        "size": "S"
    }, {
        "height": 1909,
        "size": "XXL"
    }, {
        "height": 1427,
        "size": "S"
    }, {
        "height": 1897,
        "size": "XL"
    }, {
        "height": 1605,
        "size": "S"
    }, {
        "height": 1590,
        "size": "S"
    }, {
        "height": 1654,
        "size": "M"
    }, {
        "height": 1991,
        "size": "XXL"
    }, {
        "height": 1403,
        "size": "S"
    }, {
        "height": 1403,
        "size": "S"
    }, {
        "height": 1754,
        "size": "L"
    }, {
        "height": 1806,
        "size": "XL"
    }, {
        "height": 1729,
        "size": "L"
    }, {
        "height": 1543,
        "size": "S"
    }, {
        "height": 1803,
        "size": "XL"
    }, {
        "height": 1730,
        "size": "L"
    }, {
        "height": 1645,
        "size": "S"
    }, {
        "height": 1916,
        "size": "XXL"
    }, {
        "height": 1611,
        "size": "S"
    }, {
        "height": 1864,
        "size": "XL"
    }, {
        "height": 1477,
        "size": "S"
    }, {
        "height": 1408,
        "size": "S"
    }, {
        "height": 1937,
        "size": "XXL"
    }, {
        "height": 1936,
        "size": "XXL"
    }, {
        "height": 1904,
        "size": "XXL"
    }, {
        "height": 1777,
        "size": "L"
    }, {
        "height": 1595,
        "size": "S"
    }, {
        "height": 1486,
        "size": "S"
    }, {
        "height": 1623,
        "size": "S"
    }, {
        "height": 1835,
        "size": "XL"
    }, {
        "height": 1796,
        "size": "L"
    }, {
        "height": 1582,
        "size": "S"
    }, {
        "height": 1621,
        "size": "S"
    }, {
        "height": 1622,
        "size": "S"
    }, {
        "height": 1535,
        "size": "S"
    }, {
        "height": 1817,
        "size": "XL"
    }, {
        "height": 1651,
        "size": "M"
    }, {
        "height": 1798,
        "size": "L"
    }, {
        "height": 1991,
        "size": "XXL"
    }, {
        "height": 1534,
        "size": "S"
    }, {
        "height": 1614,
        "size": "S"
    }, {
        "height": 1632,
        "size": "S"
    }, {
        "height": 1428,
        "size": "S"
    }, {
        "height": 1821,
        "size": "XL"
    }, {
        "height": 1945,
        "size": "XXL"
    }, {
        "height": 1774,
        "size": "L"
    }, {
        "height": 1621,
        "size": "S"
    }, {
        "height": 1749,
        "size": "L"
    }, {
        "height": 1887,
        "size": "XL"
    }, {
        "height": 1940,
        "size": "XXL"
    }, {
        "height": 1458,
        "size": "S"
    }, {
        "height": 1775,
        "size": "L"
    }, {
        "height": 1802,
        "size": "XL"
    }, {
        "height": 1794,
        "size": "L"
    }, {
        "height": 1409,
        "size": "S"
    }, {
        "height": 1474,
        "size": "S"
    }, {
        "height": 1449,
        "size": "S"
    }, {
        "height": 1946,
        "size": "XXL"
    }, {
        "height": 1400,
        "size": "S"
    }, {
        "height": 1526,
        "size": "S"
    }, {
        "height": 1945,
        "size": "XXL"
    }, {
        "height": 1637,
        "size": "S"
    }, {
        "height": 1752,
        "size": "L"
    }, {
        "height": 1916,
        "size": "XXL"
    }, {
        "height": 1618,
        "size": "S"
    }, {
        "height": 1679,
        "size": "M"
    }, {
        "height": 1869,
        "size": "XL"
    }, {
        "height": 1614,
        "size": "S"
    }, {
        "height": 1579,
        "size": "S"
    }, {
        "height": 1937,
        "size": "XXL"
    }, {
        "height": 1916,
        "size": "XXL"
    }, {
        "height": 1701,
        "size": "L"
    }, {
        "height": 1794,
        "size": "L"
    }, {
        "height": 1402,
        "size": "S"
    }, {
        "height": 1794,
        "size": "L"
    }, {
        "height": 1972,
        "size": "XXL"
    }, {
        "height": 1998,
        "size": "XXL"
    }, {
        "height": 1412,
        "size": "S"
    }, {
        "height": 1635,
        "size": "S"
    }, {
        "height": 1767,
        "size": "L"
    }, {
        "height": 1580,
        "size": "S"
    }, {
        "height": 1658,
        "size": "M"
    }, {
        "height": 1563,
        "size": "S"
    }, {
        "height": 1712,
        "size": "L"
    }, {
        "height": 1936,
        "size": "XXL"
    }, {
        "height": 1730,
        "size": "L"
    }, {
        "height": 1644,
        "size": "S"
    }, {
        "height": 1793,
        "size": "L"
    }, {
        "height": 1740,
        "size": "L"
    }, {
        "height": 1861,
        "size": "XL"
    }, {
        "height": 1643,
        "size": "S"
    }, {
        "height": 1554,
        "size": "S"
    }, {
        "height": 1585,
        "size": "S"
    }, {
        "height": 1435,
        "size": "S"
    }, {
        "height": 1811,
        "size": "XL"
    }, {
        "height": 1995,
        "size": "XXL"
    }, {
        "height": 1976,
        "size": "XXL"
    }, {
        "height": 1439,
        "size": "S"
    }, {
        "height": 1542,
        "size": "S"
    }, {
        "height": 1982,
        "size": "XXL"
    }, {
        "height": 1620,
        "size": "S"
    }, {
        "height": 1692,
        "size": "M"
    }, {
        "height": 1563,
        "size": "S"
    }, {
        "height": 1415,
        "size": "S"
    }, {
        "height": 1403,
        "size": "S"
    }, {
        "height": 1513,
        "size": "S"
    }, {
        "height": 1621,
        "size": "S"
    }, {
        "height": 1769,
        "size": "L"
    }, {
        "height": 1509,
        "size": "S"
    }, {
        "height": 1791,
        "size": "L"
    }, {
        "height": 1898,
        "size": "XL"
    }, {
        "height": 1468,
        "size": "S"
    }, {
        "height": 1954,
        "size": "XXL"
    }, {
        "height": 1511,
        "size": "S"
    }, {
        "height": 1529,
        "size": "S"
    }, {
        "height": 1768,
        "size": "L"
    }, {
        "height": 1874,
        "size": "XL"
    }, {
        "height": 1565,
        "size": "S"
    }, {
        "height": 1418,
        "size": "S"
    }, {
        "height": 1583,
        "size": "S"
    }, {
        "height": 1892,
        "size": "XL"
    }, {
        "height": 1799,
        "size": "L"
    }, {
        "height": 1461,
        "size": "S"
    }, {
        "height": 1497,
        "size": "S"
    }, {
        "height": 1941,
        "size": "XXL"
    }, {
        "height": 1721,
        "size": "L"
    }, {
        "height": 1789,
        "size": "L"
    }, {
        "height": 1908,
        "size": "XXL"
    }, {
        "height": 1689,
        "size": "M"
    }, {
        "height": 1853,
        "size": "XL"
    }, {
        "height": 1504,
        "size": "S"
    }, {
        "height": 1990,
        "size": "XXL"
    }, {
        "height": 1677,
        "size": "M"
    }, {
        "height": 1487,
        "size": "S"
    }, {
        "height": 1601,
        "size": "S"
    }, {
        "height": 1801,
        "size": "XL"
    }, {
        "height": 1507,
        "size": "S"
    }, {
        "height": 1555,
        "size": "S"
    }, {
        "height": 1903,
        "size": "XXL"
    }, {
        "height": 1895,
        "size": "XL"
    }, {
        "height": 1529,
        "size": "S"
    }, {
        "height": 1580,
        "size": "S"
    }, {
        "height": 1756,
        "size": "L"
    }, {
        "height": 1709,
        "size": "L"
    }, {
        "height": 1920,
        "size": "XXL"
    }, {
        "height": 1406,
        "size": "S"
    }, {
        "height": 1403,
        "size": "S"
    }, {
        "height": 1571,
        "size": "S"
    }, {
        "height": 1609,
        "size": "S"
    }, {
        "height": 1675,
        "size": "M"
    }, {
        "height": 1975,
        "size": "XXL"
    }, {
        "height": 1515,
        "size": "S"
    }, {
        "height": 1736,
        "size": "L"
    }, {
        "height": 1565,
        "size": "S"
    }, {
        "height": 1638,
        "size": "S"
    }, {
        "height": 1620,
        "size": "S"
    }, {
        "height": 1716,
        "size": "L"
    }, {
        "height": 1676,
        "size": "M"
    }, {
        "height": 1718,
        "size": "L"
    }, {
        "height": 1488,
        "size": "S"
    }, {
        "height": 1405,
        "size": "S"
    }, {
        "height": 1865,
        "size": "XL"
    }, {
        "height": 1857,
        "size": "XL"
    }, {
        "height": 1827,
        "size": "XL"
    }, {
        "height": 1650,
        "size": "S"
    }, {
        "height": 1401,
        "size": "S"
    }, {
        "height": 1659,
        "size": "M"
    }, {
        "height": 1897,
        "size": "XL"
    }, {
        "height": 1649,
        "size": "S"
    }, {
        "height": 1769,
        "size": "L"
    }, {
        "height": 1640,
        "size": "S"
    }, {
        "height": 1874,
        "size": "XL"
    }, {
        "height": 1616,
        "size": "S"
    }, {
        "height": 1811,
        "size": "XL"
    }, {
        "height": 1658,
        "size": "M"
    }, {
        "height": 1414,
        "size": "S"
    }, {
        "height": 1810,
        "size": "XL"
    }, {
        "height": 1840,
        "size": "XL"
    }, {
        "height": 1620,
        "size": "S"
    }, {
        "height": 1790,
        "size": "L"
    }, {
        "height": 1514,
        "size": "S"
    }, {
        "height": 1983,
        "size": "XXL"
    }, {
        "height": 1725,
        "size": "L"
    }, {
        "height": 1909,
        "size": "XXL"
    }, {
        "height": 1661,
        "size": "M"
    }, {
        "height": 1796,
        "size": "L"
    }, {
        "height": 1667,
        "size": "M"
    }, {
        "height": 1756,
        "size": "L"
    }, {
        "height": 1740,
        "size": "L"
    }, {
        "height": 1745,
        "size": "L"
    }, {
        "height": 1602,
        "size": "S"
    }, {
        "height": 1516,
        "size": "S"
    }, {
        "height": 1758,
        "size": "L"
    }, {
        "height": 1934,
        "size": "XXL"
    }, {
        "height": 1700,
        "size": "M"
    }, {
        "height": 1956,
        "size": "XXL"
    }, {
        "height": 1838,
        "size": "XL"
    }, {
        "height": 1675,
        "size": "M"
    }, {
        "height": 1782,
        "size": "L"
    }, {
        "height": 1954,
        "size": "XXL"
    }, {
        "height": 1967,
        "size": "XXL"
    }, {
        "height": 1611,
        "size": "S"
    }, {
        "height": 1466,
        "size": "S"
    }, {
        "height": 1705,
        "size": "L"
    }, {
        "height": 1812,
        "size": "XL"
    }, {
        "height": 1752,
        "size": "L"
    }, {
        "height": 1590,
        "size": "S"
    }, {
        "height": 1590,
        "size": "S"
    }, {
        "height": 1906,
        "size": "XXL"
    }, {
        "height": 1875,
        "size": "XL"
    }, {
        "height": 1798,
        "size": "L"
    }, {
        "height": 1787,
        "size": "L"
    }, {
        "height": 1683,
        "size": "M"
    }, {
        "height": 1520,
        "size": "S"
    }, {
        "height": 1995,
        "size": "XXL"
    }, {
        "height": 1930,
        "size": "XXL"
    }, {
        "height": 1758,
        "size": "L"
    }, {
        "height": 1954,
        "size": "XXL"
    }
]

// normalize data
var heights = []
var sizes = []

var sizeNames = ['S', 'M', 'L', 'XL', 'XXL']
data.map(item => {
    heights.push((item.height - 1400) / 600);
    sizes.push(sizeNames.indexOf(item.size));
})

let xs = tf.tensor1d(heights);
let sizesTensor = tf.tensor1d(sizes, 'int32');
let ys = tf.oneHot(sizesTensor, 5);

// Create model
let model = tf.sequential();

let hidden = tf.layers.dense({
    units: 16,
    activation: "sigmoid",
    inputDim: 1,
})

let output = tf.layers.dense({
    units: 5,
    activation: "softmax",
})

model.add(hidden)
model.add(output)

model.compile({
    optimizer: tf.train.sgd(0.2),
    loss: 'categoricalCrossentropy'
})


async function train() {
    let options = {
        epochs: 100,
        validationSplit: 0.1,
        shuffle: true,
    }

    return await model.fit(xs, ys, options);
}
console.log('Training start')
train().then(result => {
    console.log('Training finished')

    let heightTextBox = document.getElementById('height')
    let getResultBtn = document.getElementById('getResult')
    let resultText = document.getElementById('resultText')

    getResultBtn.addEventListener('click', function() {
        let height = heightTextBox.value;
        let heightInput = (height - 1400) / 600;
        let heightInputTensor = tf.tensor1d([heightInput])
        let predictResult = model.predict(heightInputTensor)
        let max = predictResult.argMax(1).dataSync()[0]
        resultText.innerHTML = "Size ao la" + sizeNames[max]
    })
})

// Train model

// Give suggest